# Generated by Django 3.0.6 on 2020-05-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Destinaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pics')),
                ('tourtype', models.CharField(choices=[('INTERNATIONAL', 'INTERNATIONAL'), ('DOMESTIC', 'DOMESTIC')], max_length=20)),
            ],
        ),
    ]
