# Generated by Django 3.0.6 on 2020-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinaion',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='destinaion',
            name='lng',
            field=models.IntegerField(null=True),
        ),
    ]
