# Generated by Django 3.0.6 on 2020-05-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200510_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinaion',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='destinaion',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
